repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287  # Use the latest stable version available
    hooks:
      - id: ruff
        args: [--fix, --config, .code_config/ruff.toml]
      - id: ruff-format
        args: [--config, .code_config/ruff.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982  # Use the latest stable version available
    hooks:
      - id: mypy
        types: [python]
        pass_filenames: false
        language: system
