name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  format:
    name: Code Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          pip install black

      - name: Run Black
        run: |
          black --check . # Check code formatting

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version you want to use

      # install poetry
      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Poetry Packages
        run: |
          poetry install
      
      - name: Activate Poetry Environment
        run: |
          poetry shell

      - name: Run tests
        run: |
          pytest  # Run your tests
